export const GQL_ERROR_CODES = {
  BAD_REQUEST: 'BAD_REQUEST',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  NOT_FOUND: 'NOT_FOUND',
  CONFLICT: 'CONFLICT',
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
  BAD_GATEWAY: 'BAD_GATEWAY',
  SERVICE_UNAVAILABLE: 'SERVICE_UNAVAILABLE',
  GATEWAY_TIMEOUT: 'GATEWAY_TIMEOUT',
  NETWORK_CONNECT_TIMEOUT_ERROR: 'NETWORK_CONNECT_TIMEOUT_ERROR',
  NETWORK_CONNECT_ERROR: 'NETWORK_CONNECT_ERROR',
  NETWORK_TIMEOUT_ERROR: 'NETWORK_TIMEOUT_ERROR',
  NETWORK_ERROR: 'NETWORK_ERROR',
  UNKNOWN_ERROR: 'UNKNOWN_ERROR',
};

// TODO: COnvert to enum. It fails right now if it is enum
